modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
[[mods]]
modId="mainport"
version="${file.jarVersion}"
displayName="MainPort"
credits=""
authors="OneLousyDev"
description='''A mod which will contain all the blocks, items, entities etc I need to port before separating them into their respective mods! :)'''
[[dependencies.mainports]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mainports]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"